name: jaqpot-models
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyter
  - numpy
  - pandas
  - scikit-learn=1.1.0
  - rdkit=2022.09.1
  - mordred
  - skl2onnx
  - onnxruntime
  - pip:
    - jaqpotpy==1.0.79
    - PyTDC
    - install
    - -r requirements-torch.txt
    - -r requirements-torch-extras.txt
